global using Infrastructure.Dapper.Abstractions;
global using Infrastructure.Dapper.Persistence;
global using Infrastructure.Dapper.Repository;
global using Microsoft.Extensions.DependencyInjection;
global using Poc.Synchronisation.Domain;
global using Poc.Synchronisation.Domain.Abstractions;
global using Poc.Synchronisation.Domain.Models;
//global using Infrastructure.Dapper.Services.Generated;
global using Refit;
